spring:
  application:
    name: 'srv-neg-employee-configuration-v1'
  profiles.active: local

  config:
    import: env-dev.yml

  cloud:
    config:
      enabled: false
      uri: ${CLOUD_CONFIG_URL}
#    vault:
#      application:
#        name: ${spring.application.name}
#      scheme: http
#      authentication: TOKEN
#      host: localhost
#      token: 00000000-0000-0000-0000-000000000000
#      port: 8200

application:
  info:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  api:
    path: '/srv/neg/v1/employee-configuration'

  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'Error al guardar al empleado.'
        status: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        status: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'Error al actualizar al empleado.'
        status: INTERNAL_ERROR

server:
  port: 8081
  error:
    include-message: always

springdoc:
  api-docs:
    path: '${application.api.path}/openapi'

  swagger-ui:
    path: '${application.api.path}/swagger-ui.html'

eureka:
  instance:
    instance-id: ${spring.application.name}:@project.version@
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

management.endpoints.web.exposure.include: 'health'

logging:
  level:
    pe.com.relari.srv_neg_employee_configuration_v1: TRACE